const cspConfig = {
    directives: {
        childSrc: ["'self'", 'blob:'],
        connectSrc: ['*', 'blob:'],
        imgSrc: ["'self'", 'unsafe-inline', 'data: *'],
        fontSrc: ["'self'", 'data:', 'fonts.googleapis.com', 'fonts.gstatic.com'],
        objectSrc: ["'self'", 'data:', '*.googlesyndication.com'],
        mediaSrc: ["'self'", 'blob: *'],
        manifestSrc: ["'self'"],
        scriptSrc: [
            "'unsafe-inline'",
            "'self'",
            "'unsafe-eval'",
            'blob:',
            '*.dplayer.pro',
            '*.2mdn.net',
            'static.ads-twitter.com',
            'weathergroup.activehosted.com',
            '*.adnxs.com',
            '*.adsafeprotected.com',
            '*.adsrvr.org',
            '*.amp.live',
            '*.ampproject.org',
            '*.app-us1.com',
            'app.link',
            '*.beachfront.com',
            '*.branch.io',
            '*.cloudfront.net',
            '*.combotag.com',
            '*.doubleclick.net',
            '*.doubleverify.com',
            '*.everesttech.net',
            '*.evidon.com',
            '*.extend.tv',
            '*.extremereach.io',
            'connect.facebook.net',
            '*.flashtalking.com',
            '*.freewheel.tv',
            'adservice.google.com',
            'tagmanager.google.com',
            '*.google-analytics.com',
            '*.google.com',
            '*.googleapis.com',
            '*.googlesyndication.com',
            '*.googletagmanager.com',
            '*.googletagservices.com',
            '*.gstatic.com',
            '*.iasds01.com',
            '*.imrworldwide.com',
            '*.innovid.com',
            '*.insightexpressai.com',
            '*.ipredictive.com',
            '*.lkqd.net',
            '*.moatads.com',
            '*.rhythmone.com',
            '*.rubiconproject.com',
            '*.scorecardresearch.com',
            '*.segment.com',
            '*.serving-sys.com',
            '*.spotx.tv',
            '*.spotxcdn.com',
            '*.spotxchange.com',
            '*.springserve.com',
            '*.telaria.com',
            'trackcmp.net',
            '*.tremorhub.com',
            'analytics.twitter.com',
            '*.unrulymedia.com',
            '*.vindicosuite.com',
            '*.w55c.net',
            '*.yumenetworks.com'
        ],
        styleSrc: [
            "'unsafe-inline'",
            'blob:',
            "'self'",
            'fonts.googleapis.com ',
            '*.gstatic.com',
            'tagmanager.google.com',
            '*.google.com',
            '*.innovid.com'
        ],
        frameSrc: [
            '*.doubleverify.com',
            '*.dvtps.com',
            '*.facebook.com',
            '*.facebook.net',
            '*.fbsbx.com',
            '*.google.com',
            '*.googleapis.com',
            '*.googlesyndication.com',
            '*.googletagmanager.com',
            '*.gumgum.com',
            '*.imrworldwide.com',
            '*.pubmatic.com',
            '*.serving-sys.com',
        ]
    }
};

module.exports = {
    cspConfig
};
